app: test-repo
env: staging
namespace: staging
chart:
    repository: https://chart.onechart.dev
    name: onechart
    version: 0.32.0
values:
    containerPort: 8080
    image:
        repository: myappsi
        tag: 0.1.0
    probe:
        enabled: true
    replicas: 2
    resources:
        limits:
            cpu: 500m
            memory: 500Mi
        requests:
            cpu: 500m
            memory: 500Mi
    vars:
        newKey: New Value
        newKey-1: New Value
    volumes:
        - name: data
          path: /data
          size: 10Gi
          storageClass: ""
