app: test-repo
env: staging
namespace: staging
chart:
    repository: https://chart.onechart.dev
    name: onechart
    version: 0.32.0
values:
    containerPort: 8080
    image:
        repository: myappd
    probe:
        enabled: true
    replicas: 2
    vars:
        newKey: New Value
        newKey-1: New Value
