app: test-repo
env: staging
namespace: staging
chart:
    repository: https://chart.onechart.dev
    name: onechart
    version: 0.32.0
values:
    image:
        repository: myappsi
    probe:
        enabled: true
    replicas: 4
    volumes:
        - name: data
          path: /data
          size: 10Gi
          storageClass: ""
